//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDay.WebApp.Localization.App.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Room {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Room() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDay.WebApp.Localization.App.Service.Room", typeof(Room).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red room.
        /// </summary>
        public static string AInML {
            get {
                return ResourceManager.GetString("AInML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green room.
        /// </summary>
        public static string DevOps {
            get {
                return ResourceManager.GetString("DevOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue room.
        /// </summary>
        public static string IoT {
            get {
                return ResourceManager.GetString("IoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet room.
        /// </summary>
        public static string ITPro {
            get {
                return ResourceManager.GetString("ITPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange room.
        /// </summary>
        public static string WebDev {
            get {
                return ResourceManager.GetString("WebDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Workshop1 {
            get {
                return ResourceManager.GetString("Workshop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Workshop10 {
            get {
                return ResourceManager.GetString("Workshop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Workshop2 {
            get {
                return ResourceManager.GetString("Workshop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Workshop3 {
            get {
                return ResourceManager.GetString("Workshop3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Workshop4 {
            get {
                return ResourceManager.GetString("Workshop4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Workshop5 {
            get {
                return ResourceManager.GetString("Workshop5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Workshop6 {
            get {
                return ResourceManager.GetString("Workshop6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Workshop7 {
            get {
                return ResourceManager.GetString("Workshop7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Workshop8 {
            get {
                return ResourceManager.GetString("Workshop8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Workshop9 {
            get {
                return ResourceManager.GetString("Workshop9", resourceCulture);
            }
        }
    }
}
