//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDay.WebApp.Localization.Host.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class My {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal My() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDay.WebApp.Localization.Host.Views.Profile.My", typeof(My).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee.
        /// </summary>
        public static string Attendee {
            get {
                return ResourceManager.GetString("Attendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string ByLink {
            get {
                return ResourceManager.GetString("ByLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to drop the info in ticket puchase form, please, press the.
        /// </summary>
        public static string DropPayment01 {
            get {
                return ResourceManager.GetString("DropPayment01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention: you can&apos;t drop succesfully purchased ticket. You also can&apos;t withdraw the succesful payment..
        /// </summary>
        public static string DropPayment01a {
            get {
                return ResourceManager.GetString("DropPayment01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to print a ticket in order to attend AzureDay. Instead you should remember name and e-mail you have entered while registering. This information you will need to provide at the entrance to the conferense and/or workshops..
        /// </summary>
        public static string HowToUseTicket {
            get {
                return ResourceManager.GetString("HowToUseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory to complete.
        /// </summary>
        public static string isModelValid {
            get {
                return ResourceManager.GetString("isModelValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum password lenghth is 6 charachters.
        /// </summary>
        public static string isPasswordLengthValid {
            get {
                return ResourceManager.GetString("isPasswordLengthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should match.
        /// </summary>
        public static string isPasswordValid {
            get {
                return ResourceManager.GetString("isPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Lab01 {
            get {
                return ResourceManager.GetString("Lab01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ticket.
        /// </summary>
        public static string MyTicket {
            get {
                return ResourceManager.GetString("MyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password again.
        /// </summary>
        public static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by card (using kaznachey.ua).
        /// </summary>
        public static string PayByCard {
            get {
                return ResourceManager.GetString("PayByCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn&apos;t complete the purchase, you can again go to purchase form using.
        /// </summary>
        public static string PayNow {
            get {
                return ResourceManager.GetString("PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via LiqPay.
        /// </summary>
        public static string PayViaLiqPay {
            get {
                return ResourceManager.GetString("PayViaLiqPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions regarding payment, you can contact us via e-mail.
        /// </summary>
        public static string Questions01 {
            get {
                return ResourceManager.GetString("Questions01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and we will help you to solve all issues..
        /// </summary>
        public static string Questions01a {
            get {
                return ResourceManager.GetString("Questions01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! The purchase is being processed. You will receive a confirmation e-mail as soon as we will confirm the payment. You can get a purchase notification from your bank sooner, but don&apos;t worry - we will still get your payment if it was succesful..
        /// </summary>
        public static string ThankYouWait {
            get {
                return ResourceManager.GetString("ThankYouWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference ticket.
        /// </summary>
        public static string Ticket01 {
            get {
                return ResourceManager.GetString("Ticket01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop ticket.
        /// </summary>
        public static string Ticket02 {
            get {
                return ResourceManager.GetString("Ticket02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode.
        /// </summary>
        public static string TicketCode {
            get {
                return ResourceManager.GetString("TicketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TicketPrice {
            get {
                return ResourceManager.GetString("TicketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets left.
        /// </summary>
        public static string TicketsLeft {
            get {
                return ResourceManager.GetString("TicketsLeft", resourceCulture);
            }
        }
    }
}
