//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDay.WebApp.Localization.Host.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDay.WebApp.Localization.Host.Views.Profile.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price before 7th of September.
        /// </summary>
        public static string BestBefore01 {
            get {
                return ResourceManager.GetString("BestBefore01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory to complete.
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for 1 ticket.
        /// </summary>
        public static string OneTicket {
            get {
                return ResourceManager.GetString("OneTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum password lenghth is 6 charachters.
        /// </summary>
        public static string PassLength {
            get {
                return ResourceManager.GetString("PassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should match.
        /// </summary>
        public static string PassMatch {
            get {
                return ResourceManager.GetString("PassMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for.
        /// </summary>
        public static string RegisterFor {
            get {
                return ResourceManager.GetString("RegisterFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPass {
            get {
                return ResourceManager.GetString("RepeatPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info you provided in the AzureDay account will not be transfered to third parties and will be used only for your identification as AzureDay conference participant..
        /// </summary>
        public static string Terms01 {
            get {
                return ResourceManager.GetString("Terms01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree with these terms by creating AzureDay account..
        /// </summary>
        public static string Terms01a {
            get {
                return ResourceManager.GetString("Terms01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        public static string TicketType01 {
            get {
                return ResourceManager.GetString("TicketType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string TicketType02 {
            get {
                return ResourceManager.GetString("TicketType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register for AzureDay and be able.
        /// </summary>
        public static string ToRegister01 {
            get {
                return ResourceManager.GetString("ToRegister01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to buy a ticket for a conference,.
        /// </summary>
        public static string ToRegister01a {
            get {
                return ResourceManager.GetString("ToRegister01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please, fill in the form below..
        /// </summary>
        public static string ToRegister01b {
            get {
                return ResourceManager.GetString("ToRegister01b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string ToRegister02 {
            get {
                return ResourceManager.GetString("ToRegister02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a conference ticket.
        /// </summary>
        public static string ToRegister02a {
            get {
                return ResourceManager.GetString("ToRegister02a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and is free. After registration (creating your personal AzureDay account) you will be offered to buy a ticket..
        /// </summary>
        public static string ToRegister02b {
            get {
                return ResourceManager.GetString("ToRegister02b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that created AzureDay account will get notifications and conference news..
        /// </summary>
        public static string ToRegister03 {
            get {
                return ResourceManager.GetString("ToRegister03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your discount!.
        /// </summary>
        public static string UseYourDiscount {
            get {
                return ResourceManager.GetString("UseYourDiscount", resourceCulture);
            }
        }
    }
}
