//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDay.WebApp.Localization.Host.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDay.WebApp.Localization.Host.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About AzureDAY.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of AzureDAY is to gather professionals that already have.
        /// </summary>
        public static string About01a {
            get {
                return ResourceManager.GetString("About01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practical experience in Azure.
        /// </summary>
        public static string About01b {
            get {
                return ResourceManager.GetString("About01b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and also beginners that only embark on their Azure journey for effective knowledge sharing..
        /// </summary>
        public static string About01c {
            get {
                return ResourceManager.GetString("About01c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureDAY has.
        /// </summary>
        public static string About02a {
            get {
                return ResourceManager.GetString("About02a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separate technology threads.
        /// </summary>
        public static string About02b {
            get {
                return ResourceManager.GetString("About02b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that profoundly cover various dimensions cloud technologies have. .
        /// </summary>
        public static string About02c {
            get {
                return ResourceManager.GetString("About02c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureDAY speakers are foreign and domestic cloud experts, trainers, enthusiasts and business owners..
        /// </summary>
        public static string About03 {
            get {
                return ResourceManager.GetString("About03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureDAY is a paid event. .
        /// </summary>
        public static string About04a {
            get {
                return ResourceManager.GetString("About04a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ticket includes free coffee breaks.
        /// </summary>
        public static string About04b {
            get {
                return ResourceManager.GetString("About04b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . We have early bird discount, students&apos; discount and partners&apos; discount. .
        /// </summary>
        public static string About04c {
            get {
                return ResourceManager.GetString("About04c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During AzureDAY you can.
        /// </summary>
        public static string About05a {
            get {
                return ResourceManager.GetString("About05a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take part in practical workshops.
        /// </summary>
        public static string About05b {
            get {
                return ResourceManager.GetString("About05b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that are being held on 8th of September. Please note that if you want to participate in any workshop, you need a dedicated workshop ticket..
        /// </summary>
        public static string About05c {
            get {
                return ResourceManager.GetString("About05c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop attendance is limited by physical limits of trainer&apos;s attention, therefore we ask you to tell us which workshop you want to attend during ticket purchase. .
        /// </summary>
        public static string About06 {
            get {
                return ResourceManager.GetString("About06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the 3rd annual.
        /// </summary>
        public static string AzureDAY01 {
            get {
                return ResourceManager.GetString("AzureDAY01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud.
        /// </summary>
        public static string AzureDAY01a {
            get {
                return ResourceManager.GetString("AzureDAY01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conference in Ukraine -.
        /// </summary>
        public static string AzureDAY01b {
            get {
                return ResourceManager.GetString("AzureDAY01b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a meeting of technologies, people, experiences, innovations and professional community..
        /// </summary>
        public static string AzureDAY01c {
            get {
                return ResourceManager.GetString("AzureDAY01c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureDAY will have.
        /// </summary>
        public static string AzureDAY02 {
            get {
                return ResourceManager.GetString("AzureDAY02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separate technology threads.
        /// </summary>
        public static string AzureDAY02a {
            get {
                return ResourceManager.GetString("AzureDAY02a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that profoundly cover various dimensions cloud technologies have,.
        /// </summary>
        public static string AzureDAY02b {
            get {
                return ResourceManager.GetString("AzureDAY02b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and also a full day (8th of September).
        /// </summary>
        public static string AzureDAY02c {
            get {
                return ResourceManager.GetString("AzureDAY02c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or practical workshops..
        /// </summary>
        public static string AzureDAY02d {
            get {
                return ResourceManager.GetString("AzureDAY02d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTSIDE UKRAINE.
        /// </summary>
        public static string Icon_box_01 {
            get {
                return ResourceManager.GetString("Icon_box_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign speakers, Microsoft Most Valuable Professionals, attendees and followers from differet countries.
        /// </summary>
        public static string Icon_box_01_text {
            get {
                return ResourceManager.GetString("Icon_box_01_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDEAS AND INNOVATIONS.
        /// </summary>
        public static string Icon_box_02 {
            get {
                return ResourceManager.GetString("Icon_box_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn new ideas and innovative techniques from the best foreign and domestic experts.
        /// </summary>
        public static string Icon_box_02_text {
            get {
                return ResourceManager.GetString("Icon_box_02_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical workshops.
        /// </summary>
        public static string Icon_box_03 {
            get {
                return ResourceManager.GetString("Icon_box_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All speakers have extensive practical knowledge. You can take part in specialized practical workshops. .
        /// </summary>
        public static string Icon_box_03_text {
            get {
                return ResourceManager.GetString("Icon_box_03_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMUNITY AND CONTACTS.
        /// </summary>
        public static string Icon_box_04 {
            get {
                return ResourceManager.GetString("Icon_box_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member of cloud community and meet new colleagues, partners or employees.
        /// </summary>
        public static string Icon_box_04_text {
            get {
                return ResourceManager.GetString("Icon_box_04_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to become a partner?.
        /// </summary>
        public static string Sponsors01 {
            get {
                return ResourceManager.GetString("Sponsors01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to support AzureDAY by providing us with speakers, gifts and/or food for attendees, help with promoting our conference - let&apos;s start a partnership. .
        /// </summary>
        public static string Sponsors01a {
            get {
                return ResourceManager.GetString("Sponsors01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can learn details about partnership programs by contacting conference organizers. .
        /// </summary>
        public static string Sponsors01b {
            get {
                return ResourceManager.GetString("Sponsors01b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Sponsors01c {
            get {
                return ResourceManager.GetString("Sponsors01c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of partner will you be?.
        /// </summary>
        public static string Sponsors02 {
            get {
                return ResourceManager.GetString("Sponsors02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold partner.
        /// </summary>
        public static string Sponsors03 {
            get {
                return ResourceManager.GetString("Sponsors03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us financially by providing funds for coffee breaks and lunches of attendees..
        /// </summary>
        public static string Sponsors03a {
            get {
                return ResourceManager.GetString("Sponsors03a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift partner.
        /// </summary>
        public static string Sponsors04 {
            get {
                return ResourceManager.GetString("Sponsors04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your own gift or prizes to be distributed or raffled among attendees..
        /// </summary>
        public static string Sponsors04a {
            get {
                return ResourceManager.GetString("Sponsors04a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational partner.
        /// </summary>
        public static string Sponsors05 {
            get {
                return ResourceManager.GetString("Sponsors05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us promote AzureDAY among your partners, clients and/or employees. .
        /// </summary>
        public static string Sponsors05a {
            get {
                return ResourceManager.GetString("Sponsors05a", resourceCulture);
            }
        }
    }
}
