//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDay.WebApp.Localization.Host.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PartnerType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDay.WebApp.Localization.Host.Views.Home.PartnerType", typeof(PartnerType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронзовый партнер.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Золотой партнер.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информационный партнер.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнер по призам.
        /// </summary>
        public static string Raffle {
            get {
                return ResourceManager.GetString("Raffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серебряный партнер.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнер по докладчикам.
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технический партнер.
        /// </summary>
        public static string Tech {
            get {
                return ResourceManager.GetString("Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеральный партнер.
        /// </summary>
        public static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнер по лабораторным работам.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
